version: '3.3'

services:
  api:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ../models:/app/models
    environment:
      - MAX_TEXT_LENGTH=500
      - MODEL_PATH=models/sentiment_model.h5
      - TOKENIZER_PATH=models/tokenizer.pkl
      - HOST=0.0.0.0
      - PORT=8000
      - RELOAD=false
    restart: unless-stopped 